### ISSUE TITLE
Add mock data to remaining n-ui components

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-a11y#42]
Reach out to @GlynnPhillips for details on what components remain to be included in pa11y tests for n-ui

**Comment by GlynnPhillips** [comment]
I have started adding some details to the README, which can be seen [here](https://github.com/Financial-Times/n-ui/blob/master/README.md#a11y-testing) 

Right now only the footer is being tested because its such a simple case I will try and add a slightly harder example asap and then we can start to add everything else.

**Comment by keirog** [comment]
Tracking [remaining items for pa11y testing in n-ui](https://github.com/Financial-Times/n-ui/issues/556)

**Comment by keirog** [comment]
- [ ] testing Slack integration
