### ISSUE TITLE
Option for skipping pa11y in CI in emergencies

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-a11y#44]
@wheresrhys placeholder for doing that ^^ for a11y (and performance?).

@GlynnPhillips had a good idea to solve this, having an endpoint we can call on every CI run to check if that app should run pa11y or not, for cases when pa11y fails (rather than the tests themselves) and there's an emergency to push something to prod. This would allow devs to turn pa11y off for a specific app for 5-10 min, without having to worry about or forget to turn it back on.

**Comment by GlynnPhillips** [comment]
@keirog made a good point about this approach, this will mean we have another dependency to up keep and rely on for builds.

This means we have another thing that might break builds but I think we could build this in a way so it doesn't fail builds if it fell over (just skips pa11y and alerts it to slack?)

This also made me think that it feels like we are fixing the wrong problem and should maybe thinking about what's failing? Pa11y CI is fairly young and is this where the issue is? If it is can we put out efforts into improving it?

Sorry my brain is a bit all over the place today so that might not make a huge amount of sense but I can explain myself after better the holidays based on this rambling mess.
