### ISSUE TITLE
Font too light in myFT tour

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-a11y#73]
AAA and only affects supernova users, but worth checking out

<img width="585" alt="screen shot 2017-01-28 at 07 50 26" src="https://cloud.githubusercontent.com/assets/3425322/22395199/7f5f3554-e52e-11e6-819b-d6dec28033b5.png">

**Comment by andygout** [comment]
Presumably this also applies to the same cards within the myFT Explore page (where contrast is ever-so-slightly worse because of the darker background)?

In any case will require some design input before we can implement.

#### myFT tour
![myft-tour](https://cloud.githubusercontent.com/assets/10484515/22689291/2bb47d54-ed28-11e6-87be-5d5023b66d54.png)

#### myFT Explore page
![myft-explore](https://cloud.githubusercontent.com/assets/10484515/22689296/301146f2-ed28-11e6-8817-251e741e38be.png)

**Comment by lc512k** [comment]
https://trello.com/c/Lmcd0Cw3/1-font-too-light-in-myft-tour
